### PR TITLE
Allow to compile non-js node_modules (coffeescript, etc)

### PR DESCRIPTION
**Pull request by goshacmd**
Ref: https://github.com/brunch/brunch/issues/1309

Requires: https://github.com/brunch/brunch/pull/1353

### CODE REVIEW

**Comment by goshacmd** [comment]
@jahbini These PR should make your use case possible. I've tested locally with a dead simple skeleton plus a super simple npm package in coffeescript, and it seemed to work.

The only piece of config required is enabling coffeescript for npm processing:

``` javascript
module.exports = {
  // See http://brunch.io for documentation.
  files: {
    javascripts: {joinTo: 'app.js'},
    stylesheets: {joinTo: 'app.css'},
    templates: {joinTo: 'app.js'}
  },
  plugins: {
    npm: ['coffee-script-brunch']
  }
}
```

**Comment by paulmillr** [comment]
plugins.npm huh?

**Comment by goshacmd** [comment]
It is actually around since two weeks ago https://github.com/brunch/brunch/pull/1318

**Comment by paulmillr** [comment]
Missed it. The naming seems too generic. Could we change it to `npm: {compilers: []}`? No `plugins`.

**Comment by jahbini** [comment]
Much appreciated.  This seems like an elegant solution that fits all the criterion

Bravo, My Compliments to The Chef.
.

**Comment by goshacmd** [comment]
@paulmillr as this adds a new public deppack method, this is going to require a minor version bump (0.6.0?)

**Pull request merged**
